apiVersion: v1
kind: Service
metadata:
  name: hotel-app-service
spec:
  selector:
    app: hotel-app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer #Eugen: LoadBalancer for our POD