# Общий алиас для ограничений выполнения
.testing-and-staging-only: &testing-and-staging-only
  only:
    - master
    - tags
    - /^fix_.*$/
    - /^feature_.*$/
    - /^infra_.*$/
  tags:
    - docker

# Этапы пайплайна
stages:
  - build
  - test
  - publish
  - clean

# Сборка первого микросервиса
build-microservice-hotel-app:
  <<: *testing-and-staging-only
  stage: build
  variables:
    MAVEN_CLI_OPTS: "-B -Dmaven.test.skip=true"
    SERVICE_NAME: "hotel-app"
  script:
    - echo "Building $SERVICE_NAME"
    - mvn $MAVEN_CLI_OPTS clean package -f ./hotel-app/pom.xml
    - mkdir -p .ci_status && touch .ci_status/build_success_hotel-app
  artifacts:
    paths:
      - ./hotel-app/target/*.jar
      - .ci_status/

# Сборка второго микросервиса
build-microservice-plugin-chat:
  <<: *testing-and-staging-only
  stage: build
  variables:
    MAVEN_CLI_OPTS: "-B -Dmaven.test.skip=true"
    SERVICE_NAME: "plugin-chat"
  script:
    - echo "Building $SERVICE_NAME"
    - mvn $MAVEN_CLI_OPTS clean package -f ./plugin-chat/pom.xml
    - mkdir -p .ci_status && touch .ci_status/build_success_plugin-chat
  artifacts:
    paths:
      - ./plugin-chat/target/*.jar

# Тестирование с использованием Docker Compose
test:
  <<: *testing-and-staging-only
  stage: test
  services:
    - docker:dind
  before_script:
    - echo "Starting Docker Compose tests"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f docker-compose.yml pull
  script:
    - docker-compose -f docker-compose.yml up -d
    - docker-compose -f docker-compose.yml ps
    - echo "Running integration tests..."
    - docker-compose -f docker-compose.yml exec -T hotel-app curl -f http://localhost:8080/health
    - docker-compose -f docker-compose.yml exec -T hotel-chat curl -f http://localhost:8081/health
    - docker-compose -f docker-compose.yml exec -T hotel-menu curl -f http://localhost:8082/health
  after_script:
    - echo "Stopping and cleaning up Docker Compose"
    - docker-compose -f docker-compose.yml down
  dependencies:
    - build-hotel-app
    - build-plugin-chat
    - build-plugin-menu
  artifacts:
    paths:
      - docker-compose.logs
        
        
# Публикация Docker-образов для всех микросервисов
publish-microservices:
  <<: *testing-and-staging-only
  stage: publish
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "Publishing Docker images"

    # Docker-образ для hotel-app
    - if [ ! -e .ci_status/build_success_hotel-app ]; then echo "Build for hotel-app must be successful!"; exit 1 ; fi
    - docker build -t $CI_REGISTRY_IMAGE/hotel-app:$CI_COMMIT_REF_SLUG -f ./hotel-app/Dockerfile ./hotel-app
    - docker push $CI_REGISTRY_IMAGE/hotel-app:$CI_COMMIT_REF_SLUG

    # Docker-образ для plugin-chat
    - if [ ! -e .ci_status/build_success_plugin-chat ]; then echo "Build for plugin-chat must be successful!"; exit 1 ; fi
    - docker build -t $CI_REGISTRY_IMAGE/plugin-chat:$CI_COMMIT_REF_SLUG -f ./plugin-chat/Dockerfile ./plugin-chat
    - docker push $CI_REGISTRY_IMAGE/plugin-chat:$CI_COMMIT_REF_SLUG

    # Docker-образ для plugin-menu
    - if [ ! -e .ci_status/build_success_plugin-menu ]; then echo "Build for plugin-menu must be successful!"; exit 1 ; fi
    - docker build -t $CI_REGISTRY_IMAGE/plugin-menu:$CI_COMMIT_REF_SLUG -f ./plugin-menu/Dockerfile ./plugin-menu
    - docker push $CI_REGISTRY_IMAGE/plugin-menu:$CI_COMMIT_REF_SLUG

# Очистка Docker-образов
clean:
  <<: *testing-and-staging-only
  stage: clean
  script:
    - echo "Cleaning Docker images"
    - docker rmi $CI_REGISTRY_IMAGE/hotel-app:$CI_COMMIT_REF_SLUG || true
    - docker rmi $CI_REGISTRY_IMAGE/plugin-chat:$CI_COMMIT_REF_SLUG || true
    - docker rmi $CI_REGISTRY_IMAGE/plugin-menu:$CI_COMMIT_REF_SLUG || true