apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-chat
  labels:
    app: hotel-chat
spec:
  replicas: 1 #achtung
  template:
    metadata:
      name: hotel-chat
      labels:
        app: hotel-chat
    spec:
      containers:
        - name: hotel-chat
          image: getsoftware-eu/hotel-chat:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube #//application-kube.properties will be seleced
      restartPolicy: Always
  selector:
    matchLabels:
      app: hotel-chat
